apiVersion: v1
kind: Secret
metadata:
  name: ledger-secret
  namespace: portfolio-ecosystem
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASS: "postgres"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_PASS: "admin"
