server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: core-ledger

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ledger_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Best practice for production; we will use Liquibase or Flyway later
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

logging:
  level:
    root: INFO
    com.portfolio.ecosystem: DEBUG
